# Generated by Django 3.2.13 on 2022-07-08 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_scrap_users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user')),
            ],
            options={
                'db_table': 'movies_movie_scrap_users',
            },
        ),
    ]
