# Generated by Django 3.2.13 on 2022-07-08 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_scrap_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_scrap_users',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='movie_scrap_users',
            old_name='user_id',
            new_name='user',
        ),
    ]
