# Generated by Django 3.2.13 on 2022-07-08 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220708_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_genres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie')),
            ],
            options={
                'db_table': 'movies_movie_genres',
            },
        ),
    ]
