# Generated by Django 3.2.13 on 2022-07-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_genres',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie_genres',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
